image: mobiledevops/android-sdk-image:34.0.0

stages:
  - build
  - publish

build:
  stage: build
  script:
    - ./gradlew build
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'

publish:
  stage: publish
  script:
    - ./gradlew publishAndroidDebugPublicationToMavenRepository -Pgitlab_access_token=$GITLAB_TOKEN
    - ./gradlew publishAndroidReleasePublicationToMavenRepository -Pgitlab_access_token=$GITLAB_TOKEN
  variables:
    GITLAB_TOKEN: $GITLAB_TOKEN
  rules:
    - if: '$CI_COMMIT_BRANCH == "main" && $CI_COMMIT_MESSAGE =~ /^release/'