[versions]
kotlin = "2.1.20-RC3"
androidGradlePlugin = "8.7.0"
coroutines = "1.10.1"
serialization = "1.8.0"
ktlint = "11.0.0"
dokka = "2.0.0"

[libraries]
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "serialization" }
kotlinx-serialization-protobuf = { module = "org.jetbrains.kotlinx:kotlinx-serialization-protobuf", version.ref = "serialization" }

[plugins]
cocoapods = { id = "org.jetbrains.kotlin.native.cocoapods", version.ref = "kotlin" }