name: Zernikalos CI

on:
  push:
    branches: [ main ]
  workflow_dispatch:
permissions:
  packages: write
  contents: read

jobs:
  # ------------- BUILD -------------
  build:
    name: Build (Gradle)
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    container:
      image: mobiledevops/android-sdk-image:34.0.0
      options: -u root
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            .gradle
          key: gradle-${{ github.ref }}

      - name: Build
        run: ./gradlew build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-dir
          path: build

  publish-android:
    needs: build
    if: ${{ github.ref == 'refs/heads/main' && startsWith(github.event.head_commit.message, 'release') }}
    name: Publish Android artifacts
    runs-on: ubuntu-latest
    container:
      image: mobiledevops/android-sdk-image:34.0.0
      options: -u root
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}   # â†’ provide a PAT with write:packages
      GITHUB_ACTOR: ${{ github.actor }} # default GitHub Actions actor
    steps:
      - uses: actions/checkout@v4

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-dir
          path: build
      - run: ./gradlew publishAndroidDebugPublicationToMavenRepository \
               -Puser=$GITHUB_ACTOR -Paccess_token=$GITHUB_TOKEN
      - run: ./gradlew publishAndroidReleasePublicationToMavenRepository \
               -Puser=$GITHUB_ACTOR -Paccess_token=$GITHUB_TOKEN

  publish-js:
    needs: build
    if: ${{ github.ref == 'refs/heads/main' && startsWith(github.event.head_commit.message, 'release') }}
    name: Publish JS package
    runs-on: ubuntu-latest
    container:
      image: node:22-alpine
      options: -u root
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-dir
          path: build

      - name: Cache node_modules & Gradle
        uses: actions/cache@v4
        with:
          path: |
            .gradle
            node_modules
          key: deps-${{ github.ref }}

      - name: Prepare npm
        run: |
          npm install -g npm
          npm config set registry https://npm.pkg.github.com/
          npm config set //npm.pkg.github.com/:_authToken $GITHUB_TOKEN

      - name: Publish
        working-directory: build/js
        run: npm publish --workspace=@zernikalos/zernikalos
